'use client';

import * as React from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Download, Share2 } from 'lucide-react';
import type { ClinicalDocument } from '@emr/contracts';
import { api } from '@/lib/api-client';
import { qk } from '@/lib/query-client';
import { ShareDocumentDialog } from '@/features/documents/share-dialog';
import { useCan } from '@/lib/session';
import { formatBytes, formatDateTime } from '@/lib/format';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { DataList, Panel, PanelBody, PanelHeader, PageHeader } from '@/components/ui/surface';
import { Alert, Skeleton } from '@/components/ui/feedback';

/** One document, with the share controls. */
export default function DocumentPage() {
  const params = useParams<{ id: string }>();
  const canShare = useCan('document:share');
  const [sharing, setSharing] = React.useState(false);

  const { data, isLoading } = useQuery({
    queryKey: qk.document(params.id),
    queryFn: () => api.get<ClinicalDocument>(`/documents/${params.id}`),
  });

  if (isLoading || !data) return <Skeleton className="h-96 w-full" />;

  const blocked = data.virusScanStatus !== null && data.virusScanStatus !== 'CLEAN';

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4">
      <Link
        href="/documents"
        className="inline-flex w-fit items-center gap-1.5 text-xs text-ink-faint hover:text-ink"
      >
        <ArrowLeft className="size-3.5" aria-hidden />
        Documents
      </Link>

      <PageHeader
        title={data.title}
        description={
          <Link href={`/patients/${data.patientId}`} className="hover:underline">
            {data.patientName}
          </Link>
        }
        actions={
          <>
            <Button variant="secondary" disabled={blocked}>
              <Download aria-hidden />
              Download
            </Button>
            {canShare ? (
              <Button variant="primary" disabled={blocked} onClick={() => setSharing(true)}>
                <Share2 aria-hidden />
                Share securely
              </Button>
            ) : null}
          </>
        }
      />

      {blocked ? (
        <Alert tone="critical" title="This file has not passed security scanning">
          {data.virusScanStatus === 'PENDING'
            ? 'It is still being scanned. It cannot be opened or shared until that finishes.'
            : 'Scanning found a problem with this file. It cannot be opened or shared.'}
        </Alert>
      ) : null}

      <Panel>
        <PanelHeader title="Details" />
        <PanelBody>
          <DataList
            items={[
              { label: 'Type', value: data.documentType.replace(/_/g, ' ').toLowerCase() },
              { label: 'Added', value: formatDateTime(data.createdAt) },
              { label: 'Size', value: formatBytes(data.sizeBytes) },
              { label: 'Format', value: data.mimeType },
              {
                label: 'Signed by',
                value: data.signedByName ?? 'Not a signed document',
              },
              {
                label: 'Security scan',
                value: data.virusScanStatus ? (
                  <Badge tone={data.virusScanStatus === 'CLEAN' ? 'positive' : 'critical'}>
                    {data.virusScanStatus === 'CLEAN' ? 'Clean' : data.virusScanStatus}
                  </Badge>
                ) : (
                  'Generated by the clinic'
                ),
              },
            ]}
          />
        </PanelBody>
      </Panel>

      {sharing ? (
        <ShareDocumentDialog
          open
          onOpenChange={setSharing}
          documentId={data.id}
          documentType={data.documentType}
          documentTitle={data.title}
          patientName={data.patientName}
        />
      ) : null}
    </div>
  );
}
