/**
 * Supporting seed data: documents, services, the WhatsApp account, approved
 * templates, consents, and a starting audit trail.
 */

import type {
  AuditEvent,
  ClinicalDocument,
  Consent,
  MessageTemplate,
  ServiceItem,
  WhatsappAccount,
} from '@emr/contracts';

const iso = (offsetMs: number) => new Date(Date.now() + offsetMs).toISOString();
const days = (n: number) => n * 24 * 60 * 60 * 1000;
const mins = (n: number) => n * 60 * 1000;

export const SERVICES: ServiceItem[] = [
  {
    id: 's1000000-0000-4000-8000-000000000001',
    name: 'New consultation',
    code: 'NEW',
    description: 'First visit for a new complaint',
    defaultFeePaise: 60000,
    hsnSacCode: null,
    taxRateBps: 0,
    defaultDurationMinutes: 20,
    practitionerId: null,
    isActive: true,
    displayOrder: 1,
  },
  {
    id: 's1000000-0000-4000-8000-000000000002',
    name: 'Follow-up (within 14 days)',
    code: 'FU',
    description: 'Review of an existing complaint',
    defaultFeePaise: 40000,
    hsnSacCode: null,
    taxRateBps: 0,
    defaultDurationMinutes: 10,
    practitionerId: null,
    isActive: true,
    displayOrder: 2,
  },
  {
    id: 's1000000-0000-4000-8000-000000000003',
    name: 'Dressing',
    code: 'DRS',
    description: null,
    defaultFeePaise: 20000,
    hsnSacCode: null,
    taxRateBps: 0,
    defaultDurationMinutes: 10,
    practitionerId: null,
    isActive: true,
    displayOrder: 3,
  },
  {
    id: 's1000000-0000-4000-8000-000000000004',
    name: 'Injection',
    code: 'INJ',
    description: null,
    defaultFeePaise: 15000,
    hsnSacCode: null,
    taxRateBps: 0,
    defaultDurationMinutes: 5,
    practitionerId: null,
    isActive: true,
    displayOrder: 4,
  },
];

export const WHATSAPP_ACCOUNT: WhatsappAccount = {
  id: 'w1000000-0000-4000-8000-000000000001',
  displayPhoneE164: '+919000012345',
  verifiedName: 'Sunrise Family Clinic',
  // Deliberately not GREEN, so the early-warning path is visible in the UI.
  qualityRating: 'YELLOW',
  messagingTier: '1,000 conversations / 24h',
  localStorageRegion: 'India',
  isActive: true,
  connectedAt: iso(-days(210)),
};

function template(
  n: number,
  purpose: MessageTemplate['purpose'],
  name: string,
  body: string,
  status: MessageTemplate['status'],
  isPrimary: boolean,
): MessageTemplate {
  return {
    id: `t1000000-0000-4000-8000-${String(n).padStart(12, '0')}`,
    name,
    purpose,
    category: purpose === 'SHARE_LINK_OTP' ? 'AUTHENTICATION' : 'UTILITY',
    language: 'en',
    body,
    variables: ['patient_name', 'clinic_name'],
    status,
    isPrimary,
    lastCheckedAt: iso(-days(1)),
  };
}

/**
 * Two variants per purpose. Provider approval can be withdrawn without warning
 * and retroactively, so a single template per purpose would mean one rejection
 * takes that channel down entirely.
 */
export const MESSAGE_TEMPLATES: MessageTemplate[] = [
  template(1, 'APPOINTMENT_REMINDER', 'appointment_reminder_v2',
    'Hello {{1}}, this is a reminder of your appointment at {{2}} tomorrow.',
    'APPROVED', true),
  template(2, 'APPOINTMENT_REMINDER', 'appointment_reminder_alt_v1',
    'Hi {{1}} — your appointment at {{2}} is tomorrow. Reply STOP to opt out.',
    'APPROVED', false),
  template(3, 'PRESCRIPTION_READY', 'prescription_ready_v1',
    'Hello {{1}}, your prescription from {{2}} is ready. Open the secure link to view it.',
    'APPROVED', true),
  template(4, 'PRESCRIPTION_READY', 'prescription_ready_alt_v1',
    'Hi {{1}}, {{2}} has issued your prescription. Use the secure link to open it.',
    'PENDING', false),
  template(5, 'REPORT_READY', 'report_ready_v1',
    'Hello {{1}}, a report is available from {{2}}. Open the secure link to view it.',
    'APPROVED', true),
  template(6, 'FOLLOW_UP_DUE', 'follow_up_due_v1',
    'Hello {{1}}, your follow-up at {{2}} is due. Call us to book a time.',
    'PAUSED', true),
  template(7, 'FOLLOW_UP_DUE', 'follow_up_due_alt_v1',
    'Hi {{1}} — {{2}} suggested a follow-up visit. Please get in touch.',
    'APPROVED', false),
  template(8, 'SHARE_LINK_OTP', 'share_link_otp_v1',
    'Your verification code for {{2}} is {{1}}. It expires in 10 minutes.',
    'APPROVED', true),
];

export function seedDocuments(
  patientId: string,
  patientName: string,
  doctorName: string,
): ClinicalDocument[] {
  return [
    {
      id: 'd1000000-0000-4000-8000-000000000001',
      patientId,
      patientName,
      encounterId: null,
      documentType: 'PRESCRIPTION',
      title: 'Prescription, 15 July',
      description: null,
      mimeType: 'application/pdf',
      sizeBytes: 148_320,
      // Generated by the clinic, so it was never an untrusted upload.
      virusScanStatus: null,
      signedByName: doctorName,
      signedAt: iso(-days(62)),
      createdAt: iso(-days(62)),
    },
    {
      id: 'd1000000-0000-4000-8000-000000000002',
      patientId,
      patientName,
      encounterId: null,
      documentType: 'LAB_REPORT',
      title: 'HbA1c and lipid profile',
      description: 'Uploaded by the patient',
      mimeType: 'application/pdf',
      sizeBytes: 402_118,
      virusScanStatus: 'CLEAN',
      signedByName: null,
      signedAt: null,
      createdAt: iso(-days(58)),
    },
    {
      id: 'd1000000-0000-4000-8000-000000000003',
      patientId,
      patientName,
      encounterId: null,
      documentType: 'PATIENT_UPLOAD',
      title: 'Photo of old prescription',
      description: 'Sent on WhatsApp',
      mimeType: 'image/jpeg',
      sizeBytes: 1_284_400,
      // Still scanning — cannot be opened or shared until it is CLEAN.
      virusScanStatus: 'PENDING',
      signedByName: null,
      signedAt: null,
      createdAt: iso(-mins(40)),
    },
  ];
}

export function seedConsents(patientId: string): Consent[] {
  return [
    {
      id: 'k1000000-0000-4000-8000-000000000001',
      patientId,
      scope: 'TREATMENT',
      status: 'ACTIVE',
      policyVersion: '2026.1',
      captureMethod: 'IN_PERSON_SIGNED',
      presentedLanguage: 'en',
      grantedAt: iso(-days(1100)),
      expiresAt: null,
      withdrawnAt: null,
      withdrawnReason: null,
    },
    {
      id: 'k1000000-0000-4000-8000-000000000002',
      patientId,
      scope: 'DATA_PROCESSING',
      status: 'ACTIVE',
      policyVersion: '2026.1',
      captureMethod: 'IN_PERSON_SIGNED',
      presentedLanguage: 'en',
      grantedAt: iso(-days(1100)),
      expiresAt: null,
      withdrawnAt: null,
      withdrawnReason: null,
    },
    {
      id: 'k1000000-0000-4000-8000-000000000003',
      patientId,
      scope: 'WHATSAPP_COMMUNICATION',
      status: 'ACTIVE',
      policyVersion: '2026.1',
      captureMethod: 'DIGITAL_OTP',
      presentedLanguage: 'mr',
      grantedAt: iso(-days(400)),
      expiresAt: null,
      withdrawnAt: null,
      withdrawnReason: null,
    },
  ];
}

function event(
  n: number,
  offsetMs: number,
  actorName: string,
  actorRole: string,
  action: string,
  resourceType: string,
  resourceLabel: string,
  outcome: AuditEvent['outcome'] = 'SUCCESS',
  isElevatedVisibility = false,
): AuditEvent {
  return {
    id: `e1000000-0000-4000-8000-${String(n).padStart(12, '0')}`,
    occurredAt: iso(offsetMs),
    actorUserId: null,
    actorName,
    actorRole,
    actorType: actorRole === 'SYSTEM' ? 'SYSTEM' : 'USER',
    action,
    outcome,
    outcomeDescription: null,
    resourceType,
    resourceId: null,
    resourceLabel,
    patientId: null,
    ipAddress: '103.21.58.14',
    requestId: null,
    httpStatus: outcome === 'SUCCESS' ? 200 : 403,
    isElevatedVisibility,
  };
}

export const AUDIT_EVENTS: AuditEvent[] = [
  event(1, -mins(8), 'Dr Anjali Mehta', 'DOCTOR', 'ENCOUNTER_FINALIZED', 'encounter',
    'Consultation, Lakshmi Narayanan'),
  event(2, -mins(8), 'Dr Anjali Mehta', 'DOCTOR', 'PRESCRIPTION_SIGNED', 'prescription',
    'Prescription, Lakshmi Narayanan'),
  event(3, -mins(7), 'System', 'SYSTEM', 'DOCUMENT_SENT', 'communication',
    'WhatsApp to +91 98455 12300'),
  // The transparency case: management read a record they did not author.
  event(4, -mins(40), 'Vikram Sunrise Holdings', 'OWNER_ADMIN',
    'ENCOUNTER_CLINICAL_CONTENT_READ', 'encounter',
    'Consultation, Govind Rao Deshpande', 'SUCCESS', true),
  event(5, -mins(52), 'Priya Kulkarni', 'RECEPTIONIST', 'PATIENT_CREATED', 'patient',
    'Kavita Joshi'),
  // A refusal, which is exactly what an auditor is looking for.
  event(6, -mins(95), 'Priya Kulkarni', 'RECEPTIONIST',
    'ENCOUNTER_CLINICAL_CONTENT_READ', 'encounter',
    'Consultation, Lakshmi Narayanan', 'SERIOUS_FAILURE'),
  event(7, -mins(120), 'Sister Fatima Shaikh', 'NURSE_ASSISTANT', 'OBSERVATION_CREATED',
    'observation', 'Vitals, Lakshmi Narayanan'),
  event(8, -days(1), 'Vikram Sunrise Holdings', 'OWNER_ADMIN', 'EXPORT_REQUESTED',
    'export', 'Full clinic export'),
  event(9, -days(1), 'External recipient', 'EXTERNAL', 'DOCUMENT_ACCESSED_VIA_SHARE_LINK',
    'document', 'HbA1c and lipid profile'),
  event(10, -days(2), 'Dr Rakesh Iyer', 'DOCTOR', 'PRESCRIPTION_SIGNED', 'prescription',
    'Blocked — no registration number on file', 'SERIOUS_FAILURE'),
];
